[workspace]
members = ["projects/*"]
default-members = [
    "projects/diagnostic",
    "projects/diagnostic-lsp",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
