[package]
name = "diagnostic"
version = "0.5.2"
authors = ["Aster <192607617@qq.com>"]
description = "Syntax error report"
repository = "https://github.com/oovm/sub_projects"
documentation = "https://docs.rs/diagnostic"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[dependencies]
unicode-width = "0.1.10"

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
